spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://11.111.1116.11:3306/name?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400
server:
  port: 8080
  address: 0.0.0.0
